#!/bin/bash
# Contrail configuration functions

# Generate space separated list of ip:port from comma separated lists of ips

CASSANDRA_IP_PORT_LIST=$(echo $CASSANDRA_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":9160"; print}')

CASSANDRA_CQL_IP_PORT_LIST=$(echo $CASSANDRA_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":9042"; print}')

ZOOKEEPER_IP_PORT_LIST=$(echo $ZOOKEEPER_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":2181"; print}')

REDIS_IP_PORT_LIST=$(echo $REDIS_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":6379"; print}')

COLLECTOR_IP_PORT_LIST=$(echo $COLLECTOR_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":8086"; print}')

CONTROL_IP_PORT_LIST=$(echo $CONTROL_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":5269"; print}')

CONFIG_API_IP_PORT_LIST=$(echo $CONFIG_API_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":8082"; print}')

DNS_IP_PORT_LIST=$(echo $DNS_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":53"; print}')

ANALYTICS_IP_PORT_LIST=$(echo $ANALYTICS_IP_LIST | \
    awk -F "," '{for (i=1;i<=NF;i++) $i=$i":8081"; print}')


# Conditionnaly set ifmap port
IFMAP_PORT=8443
if [[ $USE_SSL == "True" ]]; then
    IFMAP_PORT=8444
fi

function _fill_keystone_options()
{
    iniset -sudo $1 KEYSTONE auth_host $KEYSTONE_AUTH_HOST
    iniset -sudo $1 KEYSTONE admin_user $CONTRAIL_ADMIN_USER
    iniset -sudo $1 KEYSTONE admin_password $CONTRAIL_ADMIN_PASSWORD
    iniset -sudo $1 KEYSTONE admin_tenant_name $CONTRAIL_ADMIN_PROJECT
    iniset -sudo $1 KEYSTONE auth_port 5000
    iniset -sudo $1 KEYSTONE auth_protocol http
    if [ "$USE_MEMCACHE" == "True" ]; then #FIXME
        iniset -sudo $config_file KEYSTONE memcache_servers '127.0.0.1:11211'
    fi
}

function _fill_rabbit_options()
{
    iniset -sudo $config_file DEFAULTS rabbit_server $RABBIT_HOST
    iniset -sudo $config_file DEFAULTS rabbit_port '5672'
    iniset -sudo $config_file DEFAULTS rabbit_user $RABBIT_USERID
    iniset -sudo $config_file DEFAULTS rabbit_password $RABBIT_PASSWORD
}

function _fill_certificate_options()
{
    if [[ "$USE_SSL" == "True" ]]; then
        iniset -sudo $1 SECURITY use_certs $USE_SSL
        iniset -sudo $1 SECURITY keyfile '/etc/contrail/ssl/private_keys/apiserver_key.pem'
        iniset -sudo $1 SECURITY certfile '/etc/contrail/ssl/certs/apiserver.pem'
        iniset -sudo $1 SECURITY ca_certs '/etc/contrail/ssl/certs/ca.pem'
    fi
}

function contrail_config_cassandra()
{
    [[ "$USE_EXTERNAL_CASSANDRA" == "False" ]] && return

    sudo sed -i "s/^\#MAX_HEAP_SIZE=.*/MAX_HEAP_SIZE=\"$CASS_MAX_HEAP_SIZE\"/" /etc/cassandra/cassandra-env.sh
    sudo sed -i "s/^\#HEAP_NEWSIZE=.*/HEAP_NEWSIZE=\"$CASS_HEAP_NEWSIZE\"/" /etc/cassandra/cassandra-env.sh
    #Fix broken java version check
    sudo sed -i 's|\\< "25"|-lt 25|' /etc/cassandra/cassandra-env.sh

    #NOTE: it isn't safe to use SERVICE_LISTEN_ADDRESS here, as cassandra can't bind 0.0.0.0
    sudo sed -i "s/listen_address:.*/listen_address: $CASSANDRA_IP/" /etc/cassandra/cassandra.yaml
    sudo sed -i "s/rpc_address:.*/rpc_address: $CASSANDRA_IP/" /etc/cassandra/cassandra.yaml

    sudo sed -i "s/seeds:.*/seeds: $CASSANDRA_IP_LIST/" /etc/cassandra/cassandra.yaml

    stop_service cassandra || true
    sudo rm -Rf /var/lib/cassandra/*
    start_service cassandra
}

function contrail_config_zookeeper()
{
    local config_file="/etc/zookeeper/conf/zoo.cfg"
    sudo sed -i '/^server.*/d' $config_file
    local i=1
    for ip in $(echo $ZOOKEEPER_IP_LIST | awk -F "," '{$1=$1; print}'); do
        if [[ "$ip" != "$ZOOKEEPER_IP" ]]; then
            echo "server.$i=$ip::2888:3888" | sudo tee -a $config_file
            ((i++))
        fi
    done

    stop_service zookeeper || true
    sudo rm -Rf /var/lib/zookeper/*
    start_service zookeeper
}

function contrail_config_redis()
{
    sudo sed -i "s/bind 127.0.0.1/bind $SERVICE_LISTEN_ADDRESS/g" /etc/redis/redis.conf
    restart_service redis-server
}

function contrail_config_api()
{
    local config_file="/etc/contrail/contrail-api.conf"
    sudo truncate -s 0 $config_file

    [[ -n $CLUSTER_ID ]] && iniset -sudo $config_file DEFAULTS cluster_id $CLUSTER_ID

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DEFAULTS ifmap_server_ip $IFMAP_IP
        iniset -sudo $config_file DEFAULTS ifmap_server_port $IFMAP_PORT
        iniset -sudo $config_file DEFAULTS ifmap_username 'api-server'
        iniset -sudo $config_file DEFAULTS ifmap_password 'api-server'
    fi

    iniset -sudo $config_file DEFAULTS multi_tenancy $MULTI_TENANCY
    iniset -sudo $config_file DEFAULTS multi_tenancy_with_rbac $MULTI_TENANCY
    iniset -sudo $config_file DEFAULTS auth keystone

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DEFAULTS disc_server_ip $DISCOVERY_IP
        iniset -sudo $config_file DEFAULTS disc_server_port 5998
    else
        iniset -sudo $config_file DEFAULTS collectors "$COLLECTOR_IP_PORT_LIST"
    fi

    iniset -sudo $config_file DEFAULTS cassandra_server_list "$CASSANDRA_IP_PORT_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_ip "$ZOOKEEPER_IP_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_port 2181

    iniset -sudo $config_file DEFAULTS listen_ip_addr $CONTRAIL_LISTEN_ADDRESS
    iniset -sudo $config_file DEFAULTS listen_port 8082

    iniset -sudo $config_file DEFAULTS log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULTS log_local 1

    _fill_keystone_options $config_file
    _fill_rabbit_options $config_file
    _fill_certificate_options $config_file
}

function contrail_config_schema()
{
    local config_file="/etc/contrail/contrail-schema.conf"
    sudo truncate -s 0 $config_file

    [[ -n $CLUSTER_ID ]] && iniset -sudo $config_file DEFAULTS cluster_id $CLUSTER_ID

    iniset -sudo $config_file DEFAULTS api_server_ip $APISERVER_IP
    iniset -sudo $config_file DEFAULTS api_server_port 8082

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DEFAULTS disc_server_ip $DISCOVERY_IP
        iniset -sudo $config_file DEFAULTS disc_server_port 5998
    else
        iniset -sudo $config_file DEFAULTS collectors "$COLLECTOR_IP_PORT_LIST"
    fi

    iniset -sudo $config_file DEFAULTS cassandra_server_list "$CASSANDRA_IP_PORT_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_ip "$ZOOKEEPER_IP_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_port 2181

    iniset -sudo $config_file DEFAULTS log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULTS log_local 1

    _fill_keystone_options $config_file
    _fill_rabbit_options $config_file
    _fill_certificate_options $config_file
}

function contrail_config_svc_monitor()
{
    local config_file="/etc/contrail/contrail-svc-monitor.conf"
    sudo truncate -s 0 $config_file

    [[ -n $CLUSTER_ID ]] && iniset -sudo $config_file DEFAULTS cluster_id $CLUSTER_ID

    iniset -sudo $config_file DEFAULTS api_server_ip $APISERVER_IP
    iniset -sudo $config_file DEFAULTS api_server_port 8082

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DEFAULTS disc_server_ip $DISCOVERY_IP
        iniset -sudo $config_file DEFAULTS disc_server_port 5998
    else
        iniset -sudo $config_file DEFAULTS collectors "$COLLECTOR_IP_PORT_LIST"
    fi

    iniset -sudo $config_file SCHEDULER analytics_server_list "$ANALYTICS_IP_PORT_LIST"
    if [[ "$MULTI_TENANCY" == "False" ]]; then
        iniset -sudo $config_file SCHEDULER aaa_mode no-auth
    fi

    iniset -sudo $config_file DEFAULTS cassandra_server_list "$CASSANDRA_IP_PORT_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_ip "$ZOOKEEPER_IP_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_port 2181

    iniset -sudo $config_file DEFAULTS log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULTS log_local 1

    _fill_keystone_options $config_file
    _fill_rabbit_options $config_file
    _fill_certificate_options $config_file
}

function contrail_config_discovery()
{
    if _vercmp $CONTRAIL_BRANCH ">=" R4.0; then
        return
    fi

    local config_file="/etc/contrail/contrail-discovery.conf"
    sudo truncate -s 0 $config_file

    iniset -sudo $config_file DEFAULTS listen_ip_addr $CONTRAIL_LISTEN_ADDRESS
    iniset -sudo $config_file DEFAULTS listen_port 5998

    iniset -sudo $config_file DEFAULTS cassandra_server_list "$CASSANDRA_IP_PORT_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_ip "$ZOOKEEPER_IP_LIST"
    iniset -sudo $config_file DEFAULTS zk_server_port 2181

    iniset -sudo $config_file DEFAULTS log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULTS log_local 1
}

function contrail_config_api_lib()
{
    local config_file="/etc/contrail/vnc_api_lib.ini"
    sudo truncate -s 0 $config_file

    iniset -sudo $config_file global WEB_SERVER $APISERVER_IP
    iniset -sudo $config_file global WEB_PORT 8082
    iniset -sudo $config_file global BASE_URL  '/'

    iniset -sudo $config_file auth AUTHN_TYPE  'keystone'
    iniset -sudo $config_file auth AUTHN_PORT  5000
    iniset -sudo $config_file auth AUTHN_SERVER $KEYSTONE_AUTH_HOST
}

function contrail_config_control()
{
    local config_file="/etc/contrail/contrail-control.conf"
    sudo truncate -s 0 $config_file

    iniset -sudo $config_file DEFAULT hostname $CONTRAIL_HOSTNAME
    iniset -sudo $config_file DEFAULT hostip $CONTROL_IP

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file IFMAP user $CONTROL_IP
        iniset -sudo $config_file IFMAP password $CONTROL_IP
        iniset -sudo $config_file DISCOVERY server $DISCOVERY_IP
        iniset -sudo $config_file DISCOVERY port 5998
    else
        iniset -sudo $config_file DEFAULT collectors "$COLLECTOR_IP_PORT_LIST"
        iniset -sudo $config_file CONFIGDB rabbitmq_password $RABBIT_PASSWORD
        iniset -sudo $config_file CONFIGDB rabbitmq_user $RABBIT_USERID
        iniset -sudo $config_file CONFIGDB rabbitmq_server_list $RABBIT_HOST:'5672'
        iniset -sudo $config_file CONFIGDB config_db_server_list "$CASSANDRA_CQL_IP_PORT_LIST"
    fi

    iniset -sudo $config_file DEFAULT log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULT log_local 1

    _fill_certificate_options $config_file
}

function contrail_config_collector()
{
    local config_file="/etc/contrail/contrail-collector.conf"
    sudo truncate -s 0 $config_file

    [[ -n $CLUSTER_ID ]] && iniset -sudo $config_file DATABASE cluster_id $CLUSTER_ID

    iniset -sudo $config_file DEFAULT hostip $COLLECTOR_IP
    iniset -sudo $config_file DEFAULT hostname $CONTRAIL_HOSTNAME

    if _vercmp $CONTRAIL_BRANCH "<" R3.0; then
        iniset -sudo $config_file DEFAULT cassandra_server_list "$CASSANDRA_IP_PORT_LIST"
    else
        iniset -sudo $config_file DEFAULT cassandra_server_list "$CASSANDRA_CQL_IP_PORT_LIST"
        iniset -sudo $config_file DEFAULT zookeeper_server_list "$ZOOKEEPER_IP_PORT_LIST"
    fi

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DISCOVERY server $DISCOVERY_IP
        iniset -sudo $config_file DISCOVERY port 5998
    else
        iniset -sudo $config_file API_SERVER api_server_list $CONFIG_API_IP_PORT_LIST
    fi

    iniset -sudo $config_file DEFAULT log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULT log_local 1
}

function contrail_config_analytics_api()
{
    local config_file="/etc/contrail/contrail-analytics-api.conf"
    sudo truncate -s 0 $config_file

    [[ -n $CLUSTER_ID ]] && iniset -sudo $config_file DATABASE cluster_id $CLUSTER_ID

    iniset -sudo $config_file DEFAULT host_ip $COLLECTOR_IP
    iniset -sudo $config_file DEFAULT hostname $CONTRAIL_HOSTNAME

    #REVISIT: analytics api currently fails with default value (15)
    iniset -sudo $config_file DEFAULT partitions 0

    if _vercmp $CONTRAIL_BRANCH "<" R3.0; then
        iniset -sudo $config_file DEFAULT cassandra_server_list "$CASSANDRA_IP_PORT_LIST"
    else
        iniset -sudo $config_file DEFAULT cassandra_server_list "$CASSANDRA_CQL_IP_PORT_LIST"

        if [[ "$MULTI_TENANCY" == "False" ]]; then
            iniset -sudo $config_file DEFAULT aaa_mode no-auth
        fi
    fi

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DISCOVERY server $DISCOVERY_IP
        iniset -sudo $config_file DISCOVERY port 5998
    else
        iniset -sudo $config_file API_SERVER api_server_list $CONFIG_API_IP_PORT_LIST
        iniset -sudo $config_file REDIS redis_uve_list "$REDIS_IP_PORT_LIST"
    fi

    iniset -sudo $config_file DEFAULT log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULT log_local 1
}

function contrail_config_query()
{
    local config_file="/etc/contrail/contrail-query-engine.conf"
    sudo truncate -s 0 $config_file

    [[ -n $CLUSTER_ID ]] && iniset -sudo $config_file DATABASE cluster_id $CLUSTER_ID

    iniset -sudo $config_file DEFAULT hostip $COLLECTOR_IP
    iniset -sudo $config_file DEFAULT hostname $CONTRAIL_HOSTNAME

    if _vercmp $CONTRAIL_BRANCH "<" R3.0; then
        iniset -sudo $config_file DEFAULT cassandra_server_list "$CASSANDRA_IP_PORT_LIST"
    else
        iniset -sudo $config_file DEFAULT cassandra_server_list "$CASSANDRA_CQL_IP_PORT_LIST"
    fi

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DISCOVERY server $DISCOVERY_IP
        iniset -sudo $config_file DISCOVERY port 5998
    else
        iniset -sudo $config_file DEFAULT collectors "$COLLECTOR_IP_PORT_LIST"
    fi

    iniset -sudo $config_file DEFAULT log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULT log_local 1
}

function contrail_config_dns()
{
    local config_file="/etc/contrail/dns/contrail-dns.conf"
    sudo truncate -s 0 $config_file

    local rndc_secret=$(openssl rand -base64 32)

    iniset -sudo $config_file DEFAULT hostip $CONTROL_IP
    iniset -sudo $config_file DEFAULT hostname $CONTRAIL_HOSTNAME

    iniset -sudo $config_file DEFAULT rndc_secret $rndc_secret
    iniset -sudo $config_file DEFAULT rndc_config_file 'contrail-rndc.conf'

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DISCOVERY server $DISCOVERY_IP
        iniset -sudo $config_file DISCOVERY port 5998
        iniset -sudo $config_file IFMAP user ${CONTROL_IP}.dns
        iniset -sudo $config_file IFMAP password ${CONTROL_IP}.dns
    else
        iniset -sudo $config_file DEFAULT collectors "$COLLECTOR_IP_PORT_LIST"
        iniset -sudo $config_file CONFIGDB rabbitmq_password $RABBIT_PASSWORD
        iniset -sudo $config_file CONFIGDB rabbitmq_user $RABBIT_USERID
        iniset -sudo $config_file CONFIGDB rabbitmq_server_list $RABBIT_HOST:'5672'
        iniset -sudo $config_file CONFIGDB config_db_server_list "$CASSANDRA_CQL_IP_PORT_LIST"
    fi

    iniset -sudo $config_file DEFAULT log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULT log_local 1

    sudo sed -i "s|secret.*|secret \"$rndc_secret\";|" /etc/contrail/dns/contrail-rndc.conf
    sudo sed -i "s|secret.*|secret \"$rndc_secret\";|" /etc/contrail/dns/contrail-named.conf

    sudo mkdir -p ${CONTRAIL_DEST}/build/var/run/named/
}

function contrail_config_vrouter_agent()
{
    local config_file="/etc/contrail/contrail-vrouter-agent.conf"
    sudo truncate -s 0 $config_file

    if _vercmp $CONTRAIL_BRANCH "<" R4.0; then
        iniset -sudo $config_file DISCOVERY server $DISCOVERY_IP
        iniset -sudo $config_file DISCOVERY port 5998
    else
        iniset -sudo $config_file DEFAULT collectors "$COLLECTOR_IP_PORT_LIST"
        iniset -sudo $config_file CONTROL-NODE servers "$CONTROL_IP_PORT_LIST"
        if is_service_enabled dns; then
            iniset -sudo $config_file DNS servers "$DNS_IP_PORT_LIST"
        fi
    fi

    iniset -sudo $config_file METADATA metadata_proxy_secret 'metadatasecret'
    iniset -sudo $NOVA_CONF neutron metadata_proxy_shared_secret 'metadatasecret'
    iniset -sudo $NOVA_CONF neutron service_metadata_proxy 'True'

    iniset -sudo $config_file NETWORKS control_network_ip $VHOST_INTERFACE_IP #FIXME ?

    iniset -sudo $config_file VIRTUAL-HOST-INTERFACE ip $VHOST_INTERFACE_CIDR
    iniset -sudo $config_file VIRTUAL-HOST-INTERFACE name vhost0
    iniset -sudo $config_file VIRTUAL-HOST-INTERFACE physical_interface $VHOST_INTERFACE_NAME
    if address_in_net $DEFAULT_GW $VHOST_INTERFACE_CIDR; then
        iniset -sudo $config_file VIRTUAL-HOST-INTERFACE gateway $DEFAULT_GW
    fi

    iniset -sudo $config_file SERVICE-INSTANCE netns_command $(which opencontrail-vrouter-netns)
    iniset -sudo $config_file SERVICE-INSTANCE docker_command $(which opencontrail-vrouter-docker)

    iniset -sudo $config_file DEFAULT log_file ' '
    iniset -sudo $config_file DEFAULT log_level 'SYS_DEBUG'
    iniset -sudo $config_file DEFAULT log_local 1
}

function contrail_config_heat()
{
    if is_service_enabled heat; then
        setup_package $CONTRAIL_DEST/openstack/contrail-heat -e

        iniset $HEAT_CONF DEFAULT plugin_dirs \
            "$CONTRAIL_DEST/build/$SCONS_TARGET/api-lib/vnc_api/gen/heat/resources, \
             $CONTRAIL_DEST/openstack/contrail-heat/contrail_heat/resources"
        iniset $HEAT_CONF clients_contrail user $CONTRAIL_ADMIN_USER
        iniset $HEAT_CONF clients_contrail password $CONTRAIL_ADMIN_PASSWORD
        iniset $HEAT_CONF clients_contrail tenant $CONTRAIL_ADMIN_PROJECT
        iniset $HEAT_CONF clients_contrail api_server $APISERVER_IP
        iniset $HEAT_CONF clients_contrail api_port 8082
        iniset $HEAT_CONF clients_contrail api_base_url "/"
        iniset $HEAT_CONF clients_contrail auth_host_ip $KEYSTONE_AUTH_HOST
    fi
}

function contrail_config_irond_users()
{
    if _vercmp $CONTRAIL_BRANCH ">=" R4.0; then
        return
    fi

    local config_file="/etc/ifmap-server/basicauthusers.properties"

    echo 'api-server:api-server' | sudo tee $config_file
    echo 'schema-transformer:schema-transformer' | sudo tee -a $config_file
    echo 'svc_monitor:svc_monitor' | sudo tee -a $config_file

    for ip in $(echo $CONTROL_IP_LIST | awk -F "," '{$1=$1; print}'); do
        echo "$ip:$ip" | sudo tee -a $config_file
        echo "$ip.dns:$ip.dns" | sudo tee -a $config_file
    done
    sudo service ifmap-server restart
}


function contrail_config_qemu()
{
    #FIXME: this should be handled by devstack/lib/nova_plugins/functions-libvirt
    #but for now, is_neutron_ovs_base_plugin can't be true.
    local config_file="/etc/libvirt/qemu.conf"

    if ! sudo grep -qe '^cgroup_device_acl' /etc/libvirt/qemu.conf; then
        sudo bash -c "cat >> $config_file" <<- "EOF"
			cgroup_device_acl = [
			    "/dev/null", "/dev/full", "/dev/zero",
			    "/dev/random", "/dev/urandom",
			    "/dev/ptmx", "/dev/kvm", "/dev/kqemu",
			    "/dev/rtc", "/dev/hpet","/dev/net/tun",
			]
		EOF
        if [[ ! -f /etc/init.d/libvirtd ]]; then
            LIBVIRT_DAEMON=libvirt-bin
        else
            LIBVIRT_DAEMON=libvirtd
        fi
        restart_service $LIBVIRT_DAEMON
    fi

    if virsh net-info default >/dev/null 2>&1; then
        virsh net-destroy default
        virsh net-undefine default
    fi

    if [ -f /etc/apparmor.d/abstractions/libvirt-qemu ]; then
        # Apparmor: Authorize qemu TAP hooks
	    sudo bash -c "cat >>/etc/apparmor.d/abstractions/libvirt-qemu" <<- "EOF"

			  # qemu tap hook scripts
			  /etc/qemu-ifup ixr,
			  /etc/qemu-ifdown ixr,
		EOF
    fi
}

function contrail_config_webui()
{
    local config_file="$CONTRAIL_DEST/contrail-web-core/config/config.global.js"

    if is_service_enabled ui-webs ui-jobs; then
        sed -ie "s|discoveryService\.enable.*|discoveryService\.enable = false;|" $config_file
        sed -ie "s|regions\.RegionOne.*|regions\.RegionOne = \'http://$KEYSTONE_AUTH_HOST:5000/v2.0\';|" $config_file
        sed -ie "s|identityManager\.ip.*|identityManager\.ip = \'$KEYSTONE_AUTH_HOST\';|" $config_file
    fi
}
